Refactored plugin to be compatible with more functions
LSVH/hbo-ict-inno-s2-tno pull request #25
Opened 2020-05-20 11:03 UTC by rubenshu

essif-lab_contactform7: De "index" file.
Admin/public: spreekt voor zich.
Includes: De core plugin class + loader, activator, deactivator

2020-05-20 12:13 UTC, Fleuv commented on plugins/essif-lab_contactform7/essif-lab_contactform7.php
> +if ( ! defined( 'WPINC' ) ) {
Deze check zou ook in de hoofdplugin mogen geimplenteerd worden

2020-05-20 12:29 UTC, Fleuv requested changes
Over het algemeen zie ik niet heel veel verandering, ziet er naar uit dat je de WP plugin generator heb gebruikt om de code te "refactoren". Helaas is deze tool door een of andere onbenul in elkaar geflanst en wordt de tool ook niet echt meer geupdate. Kortom die tool kan je beter niet gebruiken, kijk naar onze hoofdplugin hoe de bootstrap daarwerkt van daaruit kan je op een correcte manier de plugin door ontwikkelen.

2020-05-20 12:29 UTC, Fleuv commented on plugins/essif-lab_contactform7/admin/class-essif-lab_contactform7-admin.php
> +class Essif_Lab_contactform7_Admin {
Zou hier eerder Admin van maken en gebruik maken van namespaces zie ook hoe het gedaan is in de hoofdplugin.

2020-05-20 12:29 UTC, Fleuv commented on plugins/essif-lab_contactform7/admin/class-essif-lab_contactform7-admin.php
> + * The admin-specific functionality of the plugin.
Weet niet of het goed is om zoveel comments neer te zetten, ben er zelf geen voorstander van. Wat mij betreft maken de comments in dit bestand de paar regels aan code juist minder leesbaar. Kortom ik stem om dit soort fratsen voor nu gewoon weg te laten.

2020-05-20 12:29 UTC, Fleuv commented on plugins/essif-lab_contactform7/admin/index.php
> +<?php // Silence is golden
Als je met classes werkt is dit niet echt nodig. Daarnaast wordt/is onze plugin code toch publiek dus kan men als ze willen dit toch wel achterhalen.

...dat er een `essif-lab_contactform7/admin/`  directory is

2020-05-20 12:29 UTC, Fleuv commented on plugins/essif-lab_contactform7/public/js/essif-lab_contactform7-public.js
> +				url: 'http://localhost:8000/api/credentialverifyrequest/1',
Dit zou naar de hoofdplugin verhuisd moeten worden. Kan net zo goed deze hele file naar de hoofdplugin verplaatsen en dan de js inladen vanuit de subplugin.

2020-05-24 13:06 UTC, rubenshu commented
Closing this because it's been picked up in PR https://github.com/LSVH/hbo-ict-inno-s2-tno/pull/26

2020-05-24 13:06 UTC, closed without merging