Updates for docker-compose file
LSVH/hbo-ict-inno-s2-tno pull request #6
Opened 2020-03-24 14:56 UTC by weis999

2020-03-24 14:57 UTC, weis999 commented
Yo Luuk is dit goed?

2020-03-25 10:06 UTC, Fleuv requested changes

2020-03-25 10:06 UTC, Fleuv commented on docker/docker-compose.yml
> +      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:rw
Wat is `app.conf` en `default.conf` en hoe kom je er aan? Klopt het trouwens dat hier `:rw` achter moet?

2020-03-25 10:06 UTC, Fleuv commented on docker/docker-compose.yml
> +    environment:
Maak gebruik van [secrets](https://docs.docker.com/compose/compose-file/#secrets) zodat we gemakkelijk verschillende stages kunnen opzetten.

2020-03-25 10:06 UTC, Fleuv commented on docker/docker-compose.yml
> +      net_1:
Deze syntax is onjuist, zie [Networking in Compose](https://docs.docker.com/compose/networking/#specify-custom-networks).

2020-03-25 10:07 UTC, weis999 commented on docker/docker-compose.yml
> +      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:rw
kan iig ook ro in principe

2020-03-25 10:07 UTC, weis999 commented on docker/docker-compose.yml
> +    environment:
Okwie. met een .env zal ike doen

2020-03-25 10:08 UTC, weis999 commented on docker/docker-compose.yml
> +      net_1:
@Ufuk09 kan je hiernaar kijken?

2020-04-02 15:22 UTC, closed without merging